package constants

const (
	// CompilerHeader gets dumped out on every generated file.
	CompilerHeader = "Code auto-generated by marlow"

	// IgnoreSourceDirective is the text that, if found, will prevent marlow from compiling the source.
	IgnoreSourceDirective = "marlow:ignore"

	// LoggerStatementPrefix is prepended to every line logged during queries.
	LoggerStatementPrefix = "[marlow] "
)

var (
	// NumericCustomTypes are the types that are numeric in nature but not part og go/types basic types.
	NumericCustomTypes = []string{"time.Time", "pq.NullTime", "mysql.NullTime"}
)
